### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by SM7I** [stronnag/xtc68#2]
Trying to compile XTC68 on a Linux ubuntu 4.15.0-36-generic #3916.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux with gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

Keep getting these errors. Seems like some files are missing....

root@ubuntu:~/xtc68/xtc68# ./makeall 
gcc -O2 -DNDEBUG -O2 -m32   -c -o analyze.o analyze.c
In file included from /usr/include/string.h:25:0,
                 from chdr.h:32,
                 from analyze.c:45:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'analyze.o' failed
make: *** [analyze.o] Error 1
gcc -c -O2 -m32 -DXTC68 -DENVVAR -DHAVE_BASENAME cc.c
In file included from /usr/include/string.h:25:0,
                 from cc.c:32:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
Makefile:128: recipe for target 'cc.o' failed
make: *** [cc.o] Error 1
cc -O2 -DXTC68 -DCPLUSPLUS -m32   -c -o cexp.o cexp.c
In file included from /usr/include/setjmp.h:25:0,
                 from cexp.c:21:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'cexp.o' failed
make: *** [cexp.o] Error 1
cc -O2 -DXTC68 -DLABELDIFF -DUSELINE -DMINIX -DHOST_LITTLE_ENDIAN -m32   -c -o cbuf.o cbuf.c
In file included from /usr/include/stdio.h:27:0,
                 from jas.h:13,
                 from cbuf.c:13:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'cbuf.o' failed
make: *** [cbuf.o] Error 1
cc -DXTC68 -O2 -m32 -c -o ld.o ldold.c
In file included from /usr/include/stdio.h:27:0,
                 from ldold.c:39:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
Makefile:22: recipe for target 'ld.o' failed
make: *** [ld.o] Error 1
gcc -I. -O2 -c -m32  slbmain.c
In file included from /usr/include/stdlib.h:24:0,
                 from slb.h:56,
                 from slbmain.c:28:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
Makefile:40: recipe for target 'slbmain.o' failed
make: *** [slbmain.o] Error 1

**Comment by stronnag** [comment]
xtc68 builds ia-32 (32 bit) applications, at least until someone is prepared to address and verify any legacy assumptions about `long` v. `int`. So you need a 32bit development environment. For Ubuntu, that means:
```
sudo apt install libc6-dev-i386
```

**Comment by SM7I** [comment]
Thanks man. You just saved my life :)

**Comment by SM7I** [comment]
Solved
