### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by derek2210** [stronnag/xtc68#29]
I tried to compile XTC68, on Linux Mint 21.2 x64, which the compiler compiles okay,  but there are errors in the tools: qls, qcp

Here is ninja output: 

[4/7] Compiling C object qls.p/src_tools_qls.c.o
FAILED: qls.p/src_tools_qls.c.o 
cc -Iqls.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -O2 -Wall -Werror -pedantic -MD -MQ qls.p/src_tools_qls.c.o -MF qls.p/src_tools_qls.c.o.d -o qls.p/src_tools_qls.c.o -c ../src/tools/qls.c
../src/tools/qls.c: In function ‘checkXTcc’:
../src/tools/qls.c:69:5: error: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   69 |     read(fd, xtbuf, sizeof(xtbuf));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/tools/qls.c: In function ‘read_ql_dir’:
../src/tools/qls.c:119:14: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  119 |     *(ptr-1) = ':';
      |     ~~~~~~~~~^~~~~
../src/tools/qls.c:116:16: note: at offset -1 into destination object of size 4096 allocated by ‘calloc’
  116 |   char*  buf = calloc(1,PATH_MAX);
      |                ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[5/7] Compiling C object qcp.p/src_tools_qcp.c.o
FAILED: qcp.p/src_tools_qcp.c.o 
cc -Iqcp.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -O2 -Wall -Werror -pedantic -MD -MQ qcp.p/src_tools_qcp.c.o -MF qcp.p/src_tools_qcp.c.o.d -o qcp.p/src_tools_qcp.c.o -c ../src/tools/qcp.c
../src/tools/qcp.c: In function ‘checkXTcc’:
../src/tools/qcp.c:55:5: error: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   55 |     read(fd, xtbuf, sizeof(xtbuf));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/tools/qcp.c: In function ‘set_dataspace’:
../src/tools/qcp.c:96:5: error: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   96 |     read(fd, xtbuf, 4);
      |     ^~~~~~~~~~~~~~~~~~
../src/tools/qcp.c:99:7: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   99 |       write(fd,"XTcc", 4);
      |       ^~~~~~~~~~~~~~~~~~~
../src/tools/qcp.c:102:5: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  102 |     write(fd, &hlen, 4);
      |     ^~~~~~~~~~~~~~~~~~~
../src/tools/qcp.c: In function ‘copy_file’:
../src/tools/qcp.c:125:9: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  125 |         write(fo, buf, n);
      |         ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

**Comment by stronnag** [comment]
We can always rely on Mint to be gratuitously incompatible with everything else. 
Which version of GCC is this?

**Comment by derek2210** [comment]
GCC v11.4

**Comment by stronnag** [comment]
Build it with `clang`; it just works ...
```
## First install clang ...
CC=clang meson setup _cbuild --prefix=~/.local --strip
ninja -C _cbuild install
```

**Comment by derek2210** [comment]
Tried the command for clang, works OK.
Thank you for the help.

**Comment by stronnag** [comment]
The README has been updated to recommend clang over older GCC.
