### ISSUE TITLE
[question/bug] How to build and use?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [stronnag/xtc68#4]
I have managed to build under Ubuntu 64 bit and a 32 bit environment.

I have done:
make all
sudo move.pl

Nothing is found in /usr/local/bin

If I try to run qcc I get an error about qcpp not being found.

What do I need to do to install the compiler?

**Comment by stronnag** [comment]
```
# install binaries
sudo ./move.pl -b
# headers
sudo ./move.pl -h
# libraries (not provided in this repo, there are available elsewhere
sudo ./move.pl -l
```
iirc

**Comment by Fabrizio-Caruso** [comment]
THANKS!
I am trying to integrate qdos-gcc into my universal retro-tool-chain:
https://github.com/Fabrizio-Caruso/CROSS-CHASE

Indeed I need some libs... At least I need stdlib....

Why not include at least the std libs into this repo?

**Comment by stronnag** [comment]
> Why not include at least the std libs into this repo?

Because that's not the purpose of this repo, it's just a cross compiler, see README.md. That the headers are here is a historic accident.

**Comment by Fabrizio-Caruso** [comment]
I am also trying to figure out how to use it. Which options are available?

If I build a simple program (that does nothing other than returning 42) I get:
"
root@brizio-VirtualBox:/media/sf_Retro/xtc68# qcc ../hello2.c
Cannot open binary file: 'crt.o'
Link failed
"

**Comment by Fabrizio-Caruso** [comment]
I guess I can find crt.o in http://www.dilwyn.me.uk/c/index.html

I did a "trivial" inspection of the move.pl but I am not familiar with perl so it is not trivial enough for me :-(

I saw:
"
	if ($opt_l)
	{
	    if($misc =~ /lib_(.*)/i)
	    {
		$lnam = $1;
		system "cp -v $misc /usr/local/qdos/lib/$lnam";
	    }
	}
"
where misc is looping through something obtained from shift || '*'... 
I google shift and it looks it produces the first argument of an array... but I do not see the array...
That is where I got stuck... Some instructions could help people get started quickly. I will try to learn some perl to figure this out...

How do you test the cross compiler? 
Could you provide a simple example/instructions on how to get it to compile a trivial program (eve none with no libs) and so test it?

Does the compiler have options? Like -D to assign a macro or like -O(number) to set an optimization level?

**Comment by stronnag** [comment]
This is not a support forum -- please ask on a qdos forum.

This tracker is for bugs --- closing. No fault found.

**Comment by Fabrizio-Caruso** [comment]
Ok, sorry. Please consider including some instructions on the options and a test example.
It will help a lot user. Little extra effort on your side and big help on potential users.
Anyway, thanks for the repository!

**Comment by Fabrizio-Caruso** [comment]
I have managed to get to compile by moving and manually renaming the header and lib files into /usr/local/qdos.
The Perl script probably does that automatically... I wish I could understand it.
Is there a special place for the crt.o file?
