### ISSUE TITLE
How to use install.sh? cp cannot star 'as68/as68'... error

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [stronnag/xtc68#8]
I have downloaded the lastest version of xtc68, as well as the support (disk1) files (in support directory). I am using Lubuntob64 bit with a 32 bit dev env as suggested.

install.sh fails with multiple cannot stat errors (as68/as68, ..., ld/qld no such file...)

It does manage to just copy the support files to their target directories.

**Comment by stronnag** [comment]
works here. Please provide some basic information, like git commit and a transcript of the failing terminal session.

**Comment by Fabrizio-Caruso** [comment]
I just clone with
git clone https://github.com/stronnag/xtc68.git
No error with clone

I copy the content of 424frun1 (disk 1) into the support dir

I run install.sh and I get:
cp: cannot stat 'as68/as68': No such file or directory
... (Other similar errors)
No qcc binary is found in /usr/local/bin but I do see the support files in /usr/local/qdos/lib and include

**Comment by stronnag** [comment]
if you want support with user errors, please answer the question ...

**Comment by Fabrizio-Caruso** [comment]
Git commit is the latest (I cloned it with no option):
git log shows: master (d681f5f...)

The user error is exactly the one I wrote here: cannot stat...
Only "cannot stat" errors.

Do I need to compile the source files somehow before running ./install.sh ?
The script install.sh seems to just contain copy instructions.

**Comment by stronnag** [comment]
> Git commit is the latest (I cloned it with no option):
> git log shows: master ([d681f5f](https://github.com/stronnag/xtc68/commit/d681f5f357642ed4ca66504640b3f75906b1c3ce)...)
> 
> The user error is exactly the one I wrote here: cannot stat...
> Only "cannot stat" errors.
> 
> Do I need to compile the source files somehow before running ./install.sh ?
> The script install.sh seems to just contain copy instructions.

It depends whether you want the script to copy the files or not. If not, it will report that do not exist.

**Comment by Fabrizio-Caruso** [comment]
My question is "how to use the script"?

I have read the README.MD and I see no instructions.

**Comment by Fabrizio-Caruso** [comment]
root@brizio-VirtualBox:/home/brizio/xtc68# ./install.sh 
cp: cannot stat 'as68/as68': No such file or directory
cp: cannot stat 'c68/c68': No such file or directory
cp: cannot stat 'cc/qcc': No such file or directory
cp: cannot stat 'cpp/qcpp': No such file or directory
cp: cannot stat 'ld/qld': No such file or directory
'./support/INCLUDE_termios.h' -> '/usr/local/qdos/include/termios.h'
'./support/INCLUDE_fcntl.h' -> '/usr/local/qdos/include/fcntl.h'
'./support/INCLUDE_sys_signal.h' -> '/usr/local/qdos/include/sys/signal.h'
'./support/INCLUDE_curses.h' -> '/usr/local/qdos/include/curses.h'
'./support/INCLUDE_sys_math.h' -> '/usr/local/qdos/include/sys/math.h'
'./support/INCLUDE_liblist.h' -> '/usr/local/qdos/include/liblist.h'
'./support/LIB_libfpu.a' -> '/usr/local/qdos/lib/libfpu.a'
'./support/INCLUDE_sys_trapdefs.h' -> '/usr/local/qdos/include/sys/trapdefs.h'
'./support/INCLUDE_time.h' -> '/usr/local/qdos/include/time.h'
'./support/INCLUDE_string.h' -> '/usr/local/qdos/include/string.h'
'./support/INCLUDE_signal.h' -> '/usr/local/qdos/include/signal.h'
'./support/INCLUDE_things.h' -> '/usr/local/qdos/include/things.h'
'./support/INCLUDE_sms.h' -> '/usr/local/qdos/include/sms.h'
'./support/INCLUDE_limits.h' -> '/usr/local/qdos/include/limits.h'
'./support/INCLUDE_stdlib.h' -> '/usr/local/qdos/include/stdlib.h'
'./support/INCLUDE_basic.h' -> '/usr/local/qdos/include/basic.h'
'./support/INCLUDE_errno.h' -> '/usr/local/qdos/include/errno.h'
'./support/INCLUDE_iso646.h' -> '/usr/local/qdos/include/iso646.h'
'./support/INCLUDE_float.h' -> '/usr/local/qdos/include/float.h'
'./support/LIB_libc.a' -> '/usr/local/qdos/lib/libc.a'
'./support/LIB_libxt.a' -> '/usr/local/qdos/lib/libxt.a'
'./support/INCLUDE_sys_types.h' -> '/usr/local/qdos/include/sys/types.h'
'./support/INCLUDE_memory.h' -> '/usr/local/qdos/include/memory.h'
'./support/INCLUDE_stdio.h' -> '/usr/local/qdos/include/stdio.h'
'./support/INCLUDE_libgen.h' -> '/usr/local/qdos/include/libgen.h'
'./support/INCLUDE_sys_stat.h' -> '/usr/local/qdos/include/sys/stat.h'
'./support/INCLUDE_varargs.h' -> '/usr/local/qdos/include/varargs.h'
'./support/LIB_crespr.o' -> '/usr/local/qdos/lib/crespr.o'
'./support/INCLUDE_wctype.h' -> '/usr/local/qdos/include/wctype.h'
'./support/INCLUDE_sys_wait.h' -> '/usr/local/qdos/include/sys/wait.h'
'./support/INCLUDE_stddef.h' -> '/usr/local/qdos/include/stddef.h'
'./support/INCLUDE_unistd.h' -> '/usr/local/qdos/include/unistd.h'
'./support/INCLUDE_sys_sysdefs.h' -> '/usr/local/qdos/include/sys/sysdefs.h'
'./support/INCLUDE_pwd.h' -> '/usr/local/qdos/include/pwd.h'
'./support/INCLUDE_qdos.h' -> '/usr/local/qdos/include/qdos.h'
'./support/LIB_libxa.a' -> '/usr/local/qdos/lib/libxa.a'
'./support/LIB_libm.a' -> '/usr/local/qdos/lib/libm.a'
'./support/INCLUDE_ctype.h' -> '/usr/local/qdos/include/ctype.h'
'./support/INCLUDE_utime.h' -> '/usr/local/qdos/include/utime.h'
'./support/INCLUDE_grp.h' -> '/usr/local/qdos/include/grp.h'
'./support/INCLUDE_debug.h' -> '/usr/local/qdos/include/debug.h'
'./support/INCLUDE_qptr.h' -> '/usr/local/qdos/include/qptr.h'
'./support/INCLUDE_term.h' -> '/usr/local/qdos/include/term.h'
'./support/INCLUDE_channels.h' -> '/usr/local/qdos/include/channels.h'
'./support/LIB_crt.o' -> '/usr/local/qdos/lib/crt.o'
'./support/INCLUDE_nl_types.h' -> '/usr/local/qdos/include/nl_types.h'
'./support/INCLUDE_assert.h' -> '/usr/local/qdos/include/assert.h'
'./support/INCLUDE_nice.h' -> '/usr/local/qdos/include/nice.h'
'./support/INCLUDE_stdarg.h' -> '/usr/local/qdos/include/stdarg.h'
'./support/INCLUDE_rll.h' -> '/usr/local/qdos/include/rll.h'
'./support/INCLUDE_dirent.h' -> '/usr/local/qdos/include/dirent.h'
'./support/INCLUDE_sroff.h' -> '/usr/local/qdos/include/sroff.h'
'./support/INCLUDE_wchar.h' -> '/usr/local/qdos/include/wchar.h'
'./support/INCLUDE_sys_times.h' -> '/usr/local/qdos/include/sys/times.h'
'./support/INCLUDE_std.h' -> '/usr/local/qdos/include/std.h'
'./support/INCLUDE_ansicondef.h' -> '/usr/local/qdos/include/ansicondef.h'
'./support/INCLUDE_setjmp.h' -> '/usr/local/qdos/include/setjmp.h'
'./support/INCLUDE_math.h' -> '/usr/local/qdos/include/math.h'
'./support/INCLUDE_sys_qlib.h' -> '/usr/local/qdos/include/sys/qlib.h'
'./support/INCLUDE_unctrl.h' -> '/usr/local/qdos/include/unctrl.h'
'./support/LIB_asmstart.o' -> '/usr/local/qdos/lib/asmstart.o'
'./support/INCLUDE_locale.h' -> '/usr/local/qdos/include/locale.h'
'./support/LIB_libxc.a' -> '/usr/local/qdos/lib/libxc.a'
'./support/INCLUDE_langinfo.h' -> '/usr/local/qdos/include/langinfo.h'
